spring:
  application:
    name: restaurant

#  datasource:
#   url: jdbc:h2:file:/data/restaurant
#  username: sa
# password: password
#driverClassName: org.h2.Driver
#jpa:
#  database-platform: org.hibernate.dialect.H2Dialect

